{"neighborhood": [], "name": "Tucson Cakes", "ypid": "452275867", "hours": [], "payment_method": [], "contact": "", "location": "", "services": [], "other_link": ["http://www.tucsoncakes.com"], "aka": [], "general_info": "Professional Birthday Cakes, Wedding Cakes and Special Event Cakes made for any occasion!", "categories": ["Bakeries", "Party & Convention Decorating"]}
{"neighborhood": [], "name": "Albertsons", "ypid": "464762394", "hours": ["Mon - Sun", "6:00 am - 12:00 am"], "payment_method": ["amex, discover, master card, visa, all major credit cards"], "contact": "6363 E 22nd St, Tucson, AZ 85710", "location": "Oxford Plz", "services": [], "other_link": ["http://www.albertsons.com/pd/stores/AZ/Tucson/Tucson-22nd-and-Wilmot-959/323578476"], "aka": ["Albertsons Floral", "Albertsons Photo Finishing", "Albertsons Delicatessen", "Albertsons Food & Pharmacy"], "general_info": "Albertsons operates a chain of more than 3,200 grocery stores and drugstores in the United States. Established in 1939, the company maintains a location in Tucson, Ariz. It is a part of the SUPERVALU group of stores, which provides distribution and related logistics support services to grocery retailers throughout the U.S. The stores feature produce, meat, seafood, bakery, frozen food and deli departments. In addition, Albertsons offers general merchandise, pharmaceuticals and specialty food items. The company organizes various fundraising and community welfare programs associated with hunger relief, education, health and nutrition and environmental stewardship.", "categories": ["Grocery Stores", "Bakeries", "Pharmacies", "Delicatessens"]}
{"neighborhood": [], "name": "Traditions Bakery", "ypid": "504659060", "hours": [], "payment_method": [], "contact": "10604 N Oracle Rd, Tucson, AZ 85737", "location": "", "services": [], "other_link": [], "aka": [], "general_info": "", "categories": ["Bakeries"]}
{"neighborhood": [], "name": "Mona's Danish Bakery", "ypid": "474794408", "hours": [], "payment_method": [], "contact": "3701 W Ina Rd Ste 102, Tucson, AZ 85741", "location": "", "services": [], "other_link": [], "aka": [], "general_info": "", "categories": ["Bakeries", "Restaurants"]}
{"neighborhood": ["Civano"], "name": "Kaity Kakes", "ypid": "503804643", "hours": [], "payment_method": [], "contact": "10547 E Marchetti Loop, Tucson, AZ 85747", "location": "", "services": [], "other_link": ["http://www.kaitykakes.com"], "aka": [], "general_info": "", "categories": ["Bakeries"]}
{"neighborhood": [], "name": "Bunz In The Oven Bakery", "ypid": "496489591", "hours": [], "payment_method": [], "contact": "6781 N Thornydale Rd Ste 229, Tucson, AZ 85741", "location": "", "services": [], "other_link": ["http://www.cakegourmet.com"], "aka": ["Sonya's Bunz In The Oven Bakery"], "general_info": "", "categories": ["Bakeries"]}
{"neighborhood": [], "name": "Breadsmith", "ypid": "505606658", "hours": [], "payment_method": [], "contact": "10355 N La Canada Dr, Tucson, AZ 85737", "location": "Canada Crossroads Shopping Ctr", "services": [], "other_link": [], "aka": ["Smith Bread"], "general_info": "", "categories": ["Bakeries"]}
{"neighborhood": [], "name": "Walmart - Bakery", "ypid": "480864561", "hours": [], "payment_method": [], "contact": "7635 N La Cholla Blvd, Tucson, AZ 85741", "location": "", "services": [], "other_link": ["http://www.walmart.com"], "aka": [], "general_info": "", "categories": ["Bakeries", "Tortillas", "Pies"]}
{"neighborhood": ["Rita Ranch"], "name": "Mimi's Fine Bakery & Cafe", "ypid": "11367433", "hours": [], "payment_method": [], "contact": "8517 E Ramona Madera Ln, Tucson, AZ 85747", "location": "", "services": [], "other_link": [], "aka": [], "general_info": "", "categories": ["Bakeries", "Coffee Shops", "Restaurants"]}
{"neighborhood": [], "name": "Baker & Baker", "ypid": "17235423", "hours": [], "payment_method": [], "contact": "9041 E Seneca St, Tucson, AZ 85715", "location": "", "services": [], "other_link": [], "aka": [], "general_info": "", "categories": ["Bakeries", "Restaurants"]}
{"neighborhood": [], "name": "Gourmet Girls Gluten Free", "ypid": "468883440", "hours": ["Tue - Thu", "7:00 am - 3:00 pm", "Fri - Sat", "7:00 am - 8:00 pm", "Sun", "7:00 am - 3:00 pm"], "payment_method": ["all major credit cards"], "contact": "5845 N Oracle Rd, Tucson, AZ 85704", "location": "", "services": [], "other_link": ["http://www.gourmetgirlsglutenfree.com"], "aka": ["Gourmet Girls Gluten Free Bakery Bistro"], "general_info": "", "categories": ["Bakeries", "Breakfast, Brunch & Lunch Restaurants", "Restaurants"]}
{"neighborhood": ["Sunnyside"], "name": "El Triunfo Bakery", "ypid": "12732566", "hours": ["Mon - Sun", "6:00 am - 8:00 pm"], "payment_method": [], "contact": "6348 S Nogales Hwy, Tucson, AZ 85706", "location": "", "services": [], "other_link": [], "aka": ["Triunfo Foods"], "general_info": "", "categories": ["Bakeries", "Restaurants"]}
{"neighborhood": [], "name": "Le Bon Gateau", "ypid": "480239105", "hours": [], "payment_method": [], "contact": "4695 N Oracle Rd Ste 105, Tucson, AZ 85705", "location": "", "services": [], "other_link": [], "aka": [], "general_info": "", "categories": ["Bakeries"]}
{"neighborhood": [], "name": "Pie Bird Bakery & Cafe", "ypid": "507415686", "hours": [], "payment_method": [], "contact": "7679 E Chase Park Loop, Tucson, AZ 85710", "location": "", "services": [], "other_link": [], "aka": [], "general_info": "", "categories": ["Bakeries"]}
{"neighborhood": ["Broadway-Northeast"], "name": "Oroweat Baking Co", "ypid": "3581894", "hours": ["Mon - Fri", "8:00 am - 8:00 pm"], "payment_method": [], "contact": "7535 E Broadway Blvd, Tucson, AZ 85710", "location": "Broadway Star Shopping Ctr", "services": [], "other_link": [], "aka": ["Oroweat Baking Company"], "general_info": "", "categories": ["Bakeries", "Wholesale Bakeries"]}
{"neighborhood": ["Sunnyside"], "name": "La Estrella Bakery", "ypid": "8568636", "hours": ["Mon - Sat", "6:00 am - 7:00 pm", "Sun", "6:00 am - 2:00 pm"], "payment_method": ["discover, master card, visa, paypal, all major credit cards"], "contact": "5266 S 12th Ave, Tucson, AZ 85706", "location": "", "services": [], "other_link": ["http://laestrellabakeryincaz.com"], "aka": [], "general_info": "", "categories": ["Bakeries", "Wholesale Bakeries", "Restaurants"]}
{"neighborhood": ["Broadway-Northeast"], "name": "La Estrella Bakery Inc", "ypid": "466069419", "hours": [], "payment_method": [], "contact": "100 S Avenida De La Vis, Tucson, AZ 85710", "location": "", "services": [], "other_link": [], "aka": [], "general_info": "", "categories": ["Bakeries"]}
{"neighborhood": [], "name": "Sarges Cheesecakes", "ypid": "507402075", "hours": [], "payment_method": [], "contact": "921 N Evelyn Ave, Tucson, AZ 85710", "location": "", "services": [], "other_link": [], "aka": [], "general_info": "", "categories": ["Bakeries"]}
{"neighborhood": [], "name": "Lena's Custom Desserts", "ypid": "478638434", "hours": [], "payment_method": [], "contact": "1517 N Wilmot Rd, Tucson, AZ 85712", "location": "Dorado Ctr", "services": [], "other_link": [], "aka": [], "general_info": "", "categories": ["Bakeries"]}
{"neighborhood": ["Miracle Manor"], "name": "Conchita's Cakes", "ypid": "463717745", "hours": [], "payment_method": [], "contact": "819 W Jacinto St, Tucson, AZ 85705", "location": "", "services": [], "other_link": [], "aka": [], "general_info": "", "categories": ["Bakeries"]}
{"neighborhood": ["Mountain View"], "name": "Cakes By Clara", "ypid": "478632250", "hours": [], "payment_method": [], "contact": "3419 N 1st Ave, Tucson, AZ 85719", "location": "", "services": [], "other_link": [], "aka": [], "general_info": "", "categories": ["Bakeries", "Wedding Supplies & Services", "Restaurants"]}
{"neighborhood": [], "name": "Baker Center", "ypid": "3372596", "hours": [], "payment_method": [], "contact": "2251 N Indian Ruins Rd Ste E, Tucson, AZ 85715", "location": "", "services": [], "other_link": ["http://primenet.com"], "aka": [], "general_info": "", "categories": ["Bakeries", "Restaurants"]}
{"neighborhood": ["Barrio Hollywood"], "name": "El Rio Bakery", "ypid": "9397785", "hours": [], "payment_method": [], "contact": "901 N Grande Ave, Tucson, AZ 85745", "location": "", "services": [], "other_link": ["http://www.elriosf.com"], "aka": ["El Rio Bakery Inc", "El Rio Bakery & Mexican Food"], "general_info": "", "categories": ["Bakeries", "Restaurants"]}
{"neighborhood": ["Campus Farm"], "name": "La Baguette Bakery", "ypid": "15766647", "hours": [], "payment_method": [], "contact": "1797 E Prince Rd, Tucson, AZ 85719", "location": "", "services": [], "other_link": [], "aka": [], "general_info": "", "categories": ["Bakeries", "Wholesale Bakeries", "Restaurants"]}
